{% set name = "earthstat" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/earthstat-{{ version }}.tar.gz
  sha256: aae3599f0017b287c491294ccbeab107df7fe613afe26e0b924cfca245fa0143

build:
  entry_points:
    - earthstat = earthstat:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.9
    - rasterio
    - shapely ==2.0.3
    - numpy ==1.26.4
    - pandas ==2.2.1
    - tqdm ==4.66.2
    - geopandas ==0.14.3
    - pyproj ==3.6.1
    - cdsapi
    - xarray ==2023.11.0
    - rioxarray

test:
  imports:
    - earthstat
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/abdelrahmanamr3/earthstat"
  summary: A Python package for efficiently generating statistical datasets from raster data for spatial units.
  license: MIT
  license_file: LICENSE
  doc_url: "https://abdelrahmanamr3.github.io/earthstat"
  dev_url: "https://github.com/abdelrahmanamr3/earthstat"


extra:
  recipe-maintainers:
    - AbdelrahmanAmr3
